version: "3"

services:
  termin-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: aachen-termin-bot2:latest
    container_name: aachen-termin-bot2
    volumes:
      - "./config:/app/config"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - signal-cli-rest-api

  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-cli
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      - AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see documentation)

    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
    restart: unless-stopped
